//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class disaggregation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disaggregation()
        {
            this.disaggregation1 = new HashSet<disaggregation>();
            this.project_indicator_disaggregation = new HashSet<project_indicator_disaggregation>();
        }
    
        public int id { get; set; }
        public Nullable<int> disaggregation_id { get; set; }
        public string disaggregation_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disaggregation> disaggregation1 { get; set; }
        public virtual disaggregation disaggregation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_indicator_disaggregation> project_indicator_disaggregation { get; set; }
    }
}
