//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicator_report_planner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public indicator_report_planner()
        {
            this.partner_indicator_results = new HashSet<partner_indicator_results>();
        }
    
        public int partner_indicator_id { get; set; }
        public int report_period_id { get; set; }
        public int year_id { get; set; }
        public string q_target { get; set; }
    
        public virtual report_periods report_periods { get; set; }
        public virtual year year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_indicator_results> partner_indicator_results { get; set; }
        public virtual partner_indicators partner_indicators { get; set; }
    }
}
