//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner_challenges
    {
        public int challenge_id { get; set; }
        public long partner_report_id { get; set; }
        public int project_id { get; set; }
        public int report_period_id { get; set; }
        public int year_id { get; set; }
        public string challenge { get; set; }
        public string effect_on_implementation { get; set; }
        public string mitigative_strategy { get; set; }
        public string attachment { get; set; }
    
        public virtual project project { get; set; }
        public virtual report_periods report_periods { get; set; }
        public virtual year year { get; set; }
        public virtual partner_reports partner_reports { get; set; }
    }
}
