//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner_reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partner_reports()
        {
            this.partner_challenges = new HashSet<partner_challenges>();
            this.partner_indicator_results = new HashSet<partner_indicator_results>();
            this.project_indicator_disaggregation_result = new HashSet<project_indicator_disaggregation_result>();
            this.project_overall_rating = new HashSet<project_overall_rating>();
            this.project_risk_report = new HashSet<project_risk_report>();
        }
    
        public long partner_report_id { get; set; }
        public int project_id { get; set; }
        public int report_period_id { get; set; }
        public int year_id { get; set; }
        public bool draft { get; set; }
        public string achievements { get; set; }
        public string achievements_attachment { get; set; }
        public string lessons_learned { get; set; }
        public string lessons_learned_attachment { get; set; }
        public string next_steps { get; set; }
        public Nullable<bool> saved { get; set; }
        public Nullable<bool> submitted { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<bool> archived { get; set; }
        public string next_steps_attachment { get; set; }
        public Nullable<decimal> cumulative_expenditure { get; set; }
        public string cumulative_expenditure_attachment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_challenges> partner_challenges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_indicator_results> partner_indicator_results { get; set; }
        public virtual project project { get; set; }
        public virtual report_periods report_periods { get; set; }
        public virtual year year { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_indicator_disaggregation_result> project_indicator_disaggregation_result { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_overall_rating> project_overall_rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_risk_report> project_risk_report { get; set; }
    }
}
