//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_indicator_disaggregation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_indicator_disaggregation()
        {
            this.project_indicator_disaggregation_result = new HashSet<project_indicator_disaggregation_result>();
        }
    
        public int id { get; set; }
        public int project_indicator_id { get; set; }
        public int disaggregation_id { get; set; }
    
        public virtual disaggregation disaggregation { get; set; }
        public virtual partner_indicators partner_indicators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_indicator_disaggregation_result> project_indicator_disaggregation_result { get; set; }
    }
}
