//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.partner_indicators = new HashSet<partner_indicators>();
            this.partner_challenges = new HashSet<partner_challenges>();
            this.project_overall_rating = new HashSet<project_overall_rating>();
            this.project_risk_report = new HashSet<project_risk_report>();
            this.project_risk = new HashSet<project_risk>();
            this.partner_reports = new HashSet<partner_reports>();
        }
    
        public int project_id { get; set; }
        public int pillar_id { get; set; }
        public string project_name { get; set; }
        public string implementing_partner { get; set; }
        public string acronym { get; set; }
        public int status_id { get; set; }
        public string partnership_reference_number { get; set; }
        public string project_objectives { get; set; }
        public string expected_outcomes { get; set; }
        public Nullable<decimal> budget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_indicators> partner_indicators { get; set; }
        public virtual pillar pillar { get; set; }
        public virtual project_status project_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_challenges> partner_challenges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_overall_rating> project_overall_rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_risk_report> project_risk_report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project_risk> project_risk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partner_reports> partner_reports { get; set; }
    }
}
