//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_overall_rating
    {
        public int project_overall_rating_id { get; set; }
        public long partner_report_id { get; set; }
        public int project_id { get; set; }
        public int report_period_id { get; set; }
        public int year_id { get; set; }
        public int rating_id { get; set; }
        public string comment { get; set; }
    
        public virtual project_rating project_rating { get; set; }
        public virtual project project { get; set; }
        public virtual report_periods report_periods { get; set; }
        public virtual year year { get; set; }
        public virtual partner_reports partner_reports { get; set; }
    }
}
