//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Data_View
    {
        public long partner_report_id { get; set; }
        public string project_name { get; set; }
        public string implementing_partner { get; set; }
        public string acronym { get; set; }
        public string partnership_reference_number { get; set; }
        public string project_objectives { get; set; }
        public string expected_outcomes { get; set; }
        public string period_name { get; set; }
        public Nullable<int> year { get; set; }
        public int project_id { get; set; }
        public int report_period_id { get; set; }
        public int year_id { get; set; }
    }
}
