//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity.Data_Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebFormsIdentityDatabaseEntities : DbContext
    {
        public WebFormsIdentityDatabaseEntities()
            : base("name=WebFormsIdentityDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<report_periods> report_periods { get; set; }
        public virtual DbSet<year> years { get; set; }
        public virtual DbSet<indicator_report_planner> indicator_report_planner { get; set; }
        public virtual DbSet<partner_indicator_results> partner_indicator_results { get; set; }
        public virtual DbSet<partner_indicators> partner_indicators { get; set; }
        public virtual DbSet<pillar> pillars { get; set; }
        public virtual DbSet<project_status> project_status { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<partner_challenges> partner_challenges { get; set; }
        public virtual DbSet<project_overall_rating> project_overall_rating { get; set; }
        public virtual DbSet<project_rating> project_rating { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserRolesView> AspNetUserRolesViews { get; set; }
        public virtual DbSet<fsda_indicators> fsda_indicators { get; set; }
        public virtual DbSet<disaggregation> disaggregations { get; set; }
        public virtual DbSet<project_indicator_disaggregation> project_indicator_disaggregation { get; set; }
        public virtual DbSet<project_indicator_disaggregation_result> project_indicator_disaggregation_result { get; set; }
        public virtual DbSet<indicator_types> indicator_types { get; set; }
        public virtual DbSet<Report_Data_View> Report_Data_View { get; set; }
        public virtual DbSet<project_risk_report> project_risk_report { get; set; }
        public virtual DbSet<project_risk> project_risk { get; set; }
        public virtual DbSet<partner_reports> partner_reports { get; set; }
    }
}
